### PR TITLE
MMT-1125: Adds `Expand All` link to Variable Draft forms

### PR DESCRIPTION
**Pull request by abbottry**

### CODE REVIEW

**Comment by macrouch** [comment]
By default the link says 'Expand All', but on empty forms, all accordions are already expanded. If they are all expanded it should probably say 'Collapse All'

**Comment by abbottry** [comment]
@macrouch I changed it so that only the last one is expanded to match collections, as part of this PR.

**Comment by macrouch** [comment]
@abbottry That makes sense, but on an empty form or just one accordion, it defaults to Expanded, but the link says 'Expand All'. You have to click it twice to get it to do anything

**Comment by macrouch** [comment]
Nevermind, this behaves the same as the Collection forms

**Comment by charleshuang80** [comment]
If I click on 'Expand All', the link changes to 'Collapse All', but then when I click the accordion headers to close all the accordions on the page, the link does not change to 'Expand All'.

**Pull request closed without merging**
