### PR TITLE
MMT-3643: Keyword Picker has some styling issues where the widget isn’t initially positioned correctly.

### PR DESCRIPTION
**Pull request by dmistry1**
During SIT testing, Francell found that during the initial loading the spinner does show up but going back to the descriptive keywords the styling is messed. This was fixed by adding a loading state in the useEffect.

### CODE REVIEW

**Review by tle1989 — APPROVED** [review]

**Comment by mandyparson** [comment]
I personally see that the loading screen has gone back to looking funny when it loads. 
Screenshot 2024-04-05 at 12 16 09 PM

**Comment by dmistry1** [comment]
> I personally see that the loading screen has gone back to looking funny when it loads. Screenshot 2024-04-05 at 12 16 09 PM

I am not seeing this, can you describe how I can reproduce this

**Comment by abbottry** [comment]
@mandyparson can you make sure you've cleared your local cache of the application and try again? @tle1989 did you load this in your browser locally before approving? Did you confirm it is working?

**Comment by tle1989** [comment]
> @mandyparson can you make sure you've cleared your local cache of the application and try again? @tle1989 did you load this in your browser locally before approving? Did you confirm it is working?

For me, it looks fine, here is the screenshot
Screenshot 2024-04-10 at 9 23 26 AM

**Review by mandyparson — APPROVED** [review]

**Pull request merged**
